### ISSUE TITLE
"Update Cache resulted in an error"

### ISSUE THREAD

**Issue by mattwelke** [dr666m1/bq-extension-vscode#14]
I'm getting an error trying to follow the quickstart displayed after the extension is installed.

These are the steps:

Install Google Cloud SDK - already had it installed
Run gcloud auth application-default login - ran command to make sure I was logged in with my personal account
Install sqlite3 - ran, it said I already had it installed
Install this extension from VSCode (BigQuery Extension for VSCode) - this was the thing I did before step 1
Open a file named xxx.bq - made a file called "query.bq" and opened it
Update cache (see the usage section) - ran the command from the command pallete

I get the following error. Sorry for the image, copy paste didn't work:

![vscode_bq_error](https://user-images.githubusercontent.com/7719209/139600376-cf6489ee-50c2-4251-912d-a0fbd9cc948e.png)

System details:

OS: WSL 2 (Ubuntu)
VS Code version:
```
Version: 1.61.2 (user setup)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```
Extension version: v1.9.0

Extension output:
```
[Trace - 4:29:57 PM] Sending request 'initialize - (0)'.
[Trace - 4:29:57 PM] Received response 'initialize - (0)' in 451ms.
[Trace - 4:29:57 PM] Sending notification 'initialized'.
[Trace - 4:29:57 PM] Sending notification 'textDocument/didOpen'.
[Trace - 4:29:57 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:29:57 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:02 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:02 PM] Received request 'workspace/configuration - (0)'.
[Trace - 4:30:02 PM] Sending response 'workspace/configuration - (0)'. Processing request took 1ms
[Trace - 4:30:02 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:02 PM] Sending request 'textDocument/completion - (1)'.
[Trace - 4:30:02 PM] Received response 'textDocument/completion - (1)' in 1ms.
[Trace - 4:30:02 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:02 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:02 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:02 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:02 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:02 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:02 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:02 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:02 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:02 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:02 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:02 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:03 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:03 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:03 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:03 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:03 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:03 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:03 PM] Sending request 'textDocument/completion - (2)'.
[Trace - 4:30:03 PM] Received response 'textDocument/completion - (2)' in 1ms.
[Trace - 4:30:03 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:03 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:03 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:03 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:03 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:03 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:04 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:04 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:04 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:04 PM] Sending request 'textDocument/completion - (3)'.
[Trace - 4:30:04 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:04 PM] Received response 'textDocument/completion - (3)' in 1ms.
[Trace - 4:30:05 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:30:05 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:05 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:30:09 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:09 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:10 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:10 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:10 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:10 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:10 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:10 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:10 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:10 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:10 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:10 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:10 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:10 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:10 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:10 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:10 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:10 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:10 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:10 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:11 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:11 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:11 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:11 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:22 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:22 PM] Sending request 'textDocument/completion - (4)'.
[Trace - 4:30:22 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:22 PM] Received response 'textDocument/completion - (4)' in 1ms.
[Trace - 4:30:22 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:22 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:23 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:23 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:23 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:23 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:23 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:24 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:24 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:24 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:24 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:24 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:24 PM] Sending request 'textDocument/completion - (5)'.
[Trace - 4:30:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:24 PM] Received response 'textDocument/completion - (5)' in 1ms.
[Trace - 4:30:26 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:26 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:26 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:26 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:26 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:26 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:26 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:26 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:26 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:26 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:26 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:26 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:26 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:26 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:27 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:27 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:27 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:27 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:27 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:27 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:27 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:27 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:27 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:27 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:27 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:27 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:27 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:27 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:27 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:27 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:28 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:28 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:28 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:28 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:28 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:28 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:29 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:29 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:29 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:30:30 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:30 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:30:30 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:30:30 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:31 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:30:31 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:31 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:30:36 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:30:36 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:30:36 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:31:12 PM] Sending notification 'textDocument/didClose'.
[Trace - 4:31:13 PM] Sending notification 'textDocument/didOpen'.
[Trace - 4:31:13 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:13 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:22 PM] Sending request 'textDocument/formatting - (6)'.
[Trace - 4:31:22 PM] Received response 'textDocument/formatting - (6)' in 21ms.
[Trace - 4:31:22 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:31:22 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:23 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:31:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:24 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:31:25 PM] Sending request 'textDocument/formatting - (7)'.
[Trace - 4:31:25 PM] Received response 'textDocument/formatting - (7)' in 2ms.
[Trace - 4:31:26 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:31:26 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:26 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:31:27 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:27 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:31:29 PM] Sending request 'textDocument/formatting - (8)'.
[Trace - 4:31:29 PM] Received response 'textDocument/formatting - (8)' in 2ms.
[Trace - 4:31:29 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:31:29 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:34 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:31:34 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:34 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:31:34 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:34 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:31:35 PM] Sending request 'textDocument/hover - (9)'.
[Trace - 4:31:35 PM] Received response 'textDocument/hover - (9)' in 1ms.
[Trace - 4:31:36 PM] Sending request 'textDocument/hover - (10)'.
[Trace - 4:31:36 PM] Received response 'textDocument/hover - (10)' in 0ms.
[Trace - 4:31:36 PM] Sending request 'textDocument/hover - (11)'.
[Trace - 4:31:36 PM] Received response 'textDocument/hover - (11)' in 1ms.
[Trace - 4:31:38 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:31:38 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:38 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:31:38 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:40 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:31:40 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:40 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:31:42 PM] Sending request 'textDocument/formatting - (12)'.
[Trace - 4:31:42 PM] Received response 'textDocument/formatting - (12)' in 2ms.
[Trace - 4:31:42 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:31:42 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:53 PM] Sending request 'textDocument/hover - (13)'.
[Trace - 4:31:53 PM] Received response 'textDocument/hover - (13)' in 0ms.
[Trace - 4:31:55 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:31:56 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:56 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:31:56 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:31:56 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:56 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:31:57 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:31:57 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:31:57 PM] Sending request 'textDocument/hover - (14)'.
[Trace - 4:31:57 PM] Received response 'textDocument/hover - (14)' in 0ms.
[Trace - 4:31:59 PM] Sending request 'textDocument/hover - (15)'.
[Trace - 4:31:59 PM] Received response 'textDocument/hover - (15)' in 0ms.
[Trace - 4:32:00 PM] Sending request 'textDocument/hover - (16)'.
[Trace - 4:32:00 PM] Received response 'textDocument/hover - (16)' in 1ms.
[Trace - 4:32:00 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:00 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:01 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:01 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:01 PM] Sending request 'textDocument/completion - (17)'.
[Trace - 4:32:01 PM] Received response 'textDocument/completion - (17)' in 1ms.
[Trace - 4:32:04 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:04 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:05 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:05 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:07 PM] Sending request 'textDocument/hover - (18)'.
[Trace - 4:32:07 PM] Received response 'textDocument/hover - (18)' in 2ms.
[Trace - 4:32:08 PM] Sending request 'textDocument/hover - (19)'.
[Trace - 4:32:08 PM] Received response 'textDocument/hover - (19)' in 1ms.
[Trace - 4:32:08 PM] Sending request 'textDocument/hover - (20)'.
[Trace - 4:32:08 PM] Received response 'textDocument/hover - (20)' in 0ms.
[Trace - 4:32:09 PM] Sending request 'textDocument/hover - (21)'.
[Trace - 4:32:09 PM] Received response 'textDocument/hover - (21)' in 0ms.
[Trace - 4:32:09 PM] Sending request 'textDocument/hover - (22)'.
[Trace - 4:32:09 PM] Received response 'textDocument/hover - (22)' in 1ms.
[Trace - 4:32:10 PM] Sending request 'textDocument/hover - (23)'.
[Trace - 4:32:10 PM] Received response 'textDocument/hover - (23)' in 1ms.
[Trace - 4:32:10 PM] Sending request 'textDocument/hover - (24)'.
[Trace - 4:32:10 PM] Received response 'textDocument/hover - (24)' in 0ms.
[Trace - 4:32:11 PM] Sending request 'textDocument/hover - (25)'.
[Trace - 4:32:11 PM] Received response 'textDocument/hover - (25)' in 0ms.
[Trace - 4:32:16 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:16 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:16 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:16 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:17 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:17 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:17 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:17 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:17 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:17 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:22 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:22 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:22 PM] Sending request 'textDocument/completion - (26)'.
[Trace - 4:32:22 PM] Received response 'textDocument/completion - (26)' in 1ms.
[Trace - 4:32:22 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:22 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:23 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:23 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:23 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:24 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:24 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:24 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:24 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:24 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:24 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:32:24 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:24 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:32:41 PM] Sending request 'textDocument/hover - (27)'.
[Trace - 4:32:41 PM] Received response 'textDocument/hover - (27)' in 1ms.
[Trace - 4:32:43 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:43 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:43 PM] Sending request 'textDocument/completion - (28)'.
[Trace - 4:32:43 PM] Received response 'textDocument/completion - (28)' in 1ms.
[Trace - 4:32:43 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:43 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:44 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:44 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:44 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:44 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:45 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:45 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:45 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:45 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:45 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:45 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:46 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:46 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:46 PM] Sending request 'textDocument/completion - (29)'.
[Trace - 4:32:46 PM] Received response 'textDocument/completion - (29)' in 1ms.
[Trace - 4:32:46 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:46 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:46 PM] Sending request 'textDocument/completion - (30)'.
[Trace - 4:32:46 PM] Received response 'textDocument/completion - (30)' in 0ms.
[Trace - 4:32:46 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:46 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:46 PM] Sending request 'textDocument/completion - (31)'.
[Trace - 4:32:46 PM] Received response 'textDocument/completion - (31)' in 1ms.
[Trace - 4:32:46 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:46 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:46 PM] Sending request 'textDocument/completion - (32)'.
[Trace - 4:32:46 PM] Received response 'textDocument/completion - (32)' in 1ms.
[Trace - 4:32:46 PM] Sending notification 'textDocument/didChange'.
[Trace - 4:32:46 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:46 PM] Sending request 'textDocument/completion - (33)'.
[Trace - 4:32:46 PM] Received response 'textDocument/completion - (33)' in 0ms.
[Trace - 4:32:47 PM] Sending notification 'textDocument/didSave'.
[Trace - 4:32:47 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:32:47 PM] Received notification 'bq/totalBytesProcessed'.
[Trace - 4:33:13 PM] Sending request 'bq/updateCache - (34)'.
undefined:35
      "
       

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/matt/.vscode-server/extensions/dr666m1.bq-extension-vscode-0.0.8/server/out/database.js:121:39)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.Readable.read (internal/streams/readable.js:519:10)
    at flow (internal/streams/readable.js:992:34)
    at resume_ (internal/streams/readable.js:973:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[Info  - 4:33:14 PM] Connection to server got closed. Server will restart.
[Trace - 4:33:14 PM] Sending request 'initialize - (0)'.
[Trace - 4:33:14 PM] Received response 'initialize - (0)' in 416ms.
[Trace - 4:33:14 PM] Sending notification 'initialized'.
[Trace - 4:33:14 PM] Sending notification 'textDocument/didOpen'.
[Trace - 4:33:14 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:33:14 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 4:33:53 PM] Sending request 'textDocument/hover - (1)'.
[Trace - 4:33:53 PM] Received response 'textDocument/hover - (1)' in 1ms.
```

**Comment by dr666m1** [comment]
@mattwelke 
Thank you for bug reporting.

Apparently the error occurs when parsing the response of [BigQuery API](https://cloud.google.com/bigquery/docs/reference/rest).

I have just published new version (0.0.10) which does not use BigQuery API.
Please try the latest version.
